version = 1

[install]
nodejs_24.pkg-path = "nodejs_24"
nodejs_24.version = "^24.11.1"
go.pkg-path = "go"
go.version = "1.25.4"
protobuf.pkg-path = "protobuf"
protobuf.version = "^32.1"
go-task.pkg-path = "go-task"
go-task.version = "^3.45.5"
buf.pkg-path = "buf"
buf.version = "^1.60.0"
claude-code.pkg-path = "claude-code"
claude-code.version = "^2.0.59"
prettier.pkg-path = "prettier"
prettier.version = "^3.6.2"