version = 1

[install]
claude-code.pkg-path = "claude-code"
claude-code.version = "2.0.55"
prettier.pkg-path = "prettier"
prettier.version = "3.6.2"
nodejs_24.pkg-path = "nodejs_24"
nodejs_24.version = "24.11.1"
